# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: ci-deploy-gh-pages

on:
  schedule:
    - cron: '0 8  1 * *'  # Runs at 08:00 on day  1 of the month in UTC zone
    - cron: '0 8 15 * *'  # Runs at 08:00 on day 15 of the month in UTC zone
  workflow_dispatch:
    inputs:
      TYPE:
        description: 'Set TYPE input'
        required: true
        type: choice
        default: 'matrix'
        options:
          - 'matrix'
          - 'single'
      VERSION:
        description: 'Set VERSION input (for single type)'
        required: true
        type: string
        default: 'git-master'
      LANGUAGE:
        description: 'Set LANGUAGE input (for single type)'
        required: true
        type: string
        default: 'all'

jobs:
  get-matrix:
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.TYPE == 'matrix') ||
        (github.event_name == 'schedule')
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.rvm.outputs.VERSION }}
      LANGUAGE: ${{ steps.rll.outputs.LANGUAGE }}
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Read VERSION from matrix.json
        id: rvm
        run: |
          FILTER=".include | map(.VERSION)"
          VERSION=$(jq -c "$FILTER" .github/workflows/matrix.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION:"
          echo "$VERSION" | jq "."
      - name: Read LANGUAGE from languages.json
        id: rll
        run: |
          LANGUAGE=$(jq -c "keys" languages.json)
          echo "LANGUAGE=$LANGUAGE" >> $GITHUB_OUTPUT
          echo "LANGUAGE:"
          echo "$LANGUAGE" | jq "."

  matrix:
    needs: get-matrix
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.TYPE == 'matrix') || 
        (github.event_name == 'schedule')
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.VERSION }}-${{ matrix.LANGUAGE }}
      cancel-in-progress: true
    strategy:
      matrix: 
        VERSION: ${{ fromJson(needs.get-matrix.outputs.VERSION) }}
        # LANGUAGE: ${{ fromJson(needs.get-matrix.outputs.LANGUAGE) }}
        LANGUAGE: [ 'all' ]
      fail-fast: false
    uses: ./.github/workflows/use-deploy-gh-pages.yml
    with:
      VERSION: ${{ matrix.VERSION }}
      LANGUAGE: ${{ matrix.LANGUAGE }}
      UPDATE_MODE: 'NEVER'
      CALLER_JOB: 'matrix (${{ matrix.VERSION }}, ${{ matrix.LANGUAGE }})'
      ENABLE_JOB: true
      DEPLOY_HTML: true

  single:
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.TYPE == 'single')
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.inputs.VERSION }}-${{ github.event.inputs.LANGUAGE }}
      cancel-in-progress: true
    uses: ./.github/workflows/use-deploy-gh-pages.yml
    with:
      VERSION: ${{ github.event.inputs.VERSION }}
      LANGUAGE: ${{ github.event.inputs.LANGUAGE }}
      UPDATE_MODE: 'NEVER'
      CALLER_JOB: 'single'
      ENABLE_JOB: true
      DEPLOY_HTML: true